version: "3"

services:
  db:
    image: mysql:8.0
    restart: always
    expose:
      - "3306"
    ports:
      - "33061:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${passwordDB}
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
        - '3306:3306'
    logging:
      driver: none
    container_name: edumy_db
  app:
    platform: linux/amd64
    build: .
    command: bundle exec rails s -p 3000 -b "0.0.0.0"
    env_file:
      - .env
    environment:
      hostName: db
    volumes:
      - .:/undergraduate-api
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
volumes:
  db_data:
